variables:
  LOCAL_PROXY_SSH_PORT: 22
  LOCAL_PROXY_USER: vndeployer
  LOCAL_PROXY_SERVER: 10.10.50.69
  KBT_PROXY_SSH_PORT: 8837
  KBT_PROXY_USER: vndeployer
  KBT_PROXY_SERVER: l1deploy.starixplay.com
  SIT_PROXY_SSH_PORT: 8837
  SIT_PROXY_USER: vndeployer
  SIT_PROXY_SERVER: l1deploy.starixplay.com

  SC_SWARM_CLUSTER_LOCAL: 10.10.50.14 10.10.50.19 10.10.50.20
  SC_SWARM_LEADER_LOCAL: 10.10.50.69
  SC_SWARM_LEADER_LOCAL_SSH_PORT: 22
  SC_SWARM_LEADER_LOCAL_SSH_USER: vndeployer
  SC_SWARM_NETWORK_LOCAL: swarm_luminet_local
  DEPLOYMENT_API_LOCAL: 

  SC_SWARM_CLUSTER_SIT: 
  SC_SWARM_LEADER_SIT: 10.2.189.51
  SC_SWARM_LEADER_SIT_SSH_PORT: 8837
  SC_SWARM_LEADER_SIT_SSH_USER: vndeployer
  SC_SWARM_NETWORK_SIT: swarm_luminet_sit
  DEPLOYMENT_API_SIT: 

  SC_SWARM_CLUSTER_UAT: 
  SC_SWARM_LEADER_UAT: 10.2.189.51
  SC_SWARM_LEADER_UAT_SSH_PORT: 8837
  SC_SWARM_LEADER_UAT_SSH_USER: vndeployer
  SC_SWARM_NETWORK_UAT: swarm_luminet_sit
  DEPLOYMENT_API_UAT: 

  SC_SWARM_CLUSTER_PROD: 
  SC_SWARM_LEADER_PROD: 10.2.189.50
  SC_SWARM_LEADER_PROD_SSH_PORT: 22
  SC_SWARM_LEADER_PROD_SSH_USER: vndeployer
  SC_SWARM_NETWORK_PROD: swarm_luminet_prod
  DEPLOYMENT_API_PROD: 

  SC_SWARM_CLUSTER_AWS: 
  SC_SWARM_LEADER_AWS: 10.2.189.2
  SC_SWARM_LEADER_AWS_SSH_PORT: 22
  SC_SWARM_LEADER_AWS_SSH_USER: vndeployer
  SC_SWARM_NETWORK_AWS: swarm_luminet_aws
  DEPLOYMENT_API_AWS: 
