.base_deploy_stack_swarm:
  stage: deploy
  script:
    - curl -F host=$SERVER_IP -F port=$SERVER_PORT -F user=$SERVER_USER -F command="docker login -u $DOCKER_REG_USERNAME -p $DOCKER_REG_PASSWORD $DOCKER_REG_URL" $DEPLOYMENT_API/command?token=$DEPLOY_API_TOKEN
    - curl -F jobid=$CI_JOB_ID -F env=$DEPLOY_ENV -F host=$SERVER_IP -F port=$SERVER_PORT -F user=$SERVER_USER -F command="mkdir -p $WORKING_PATH/$DEPLOY_ENV/configs" $DEPLOYMENT_API/command?token=$DEPLOY_API_TOKEN
    - echo "===== TRANSFORM docker-compose.yml ... =====";
    - export DOCKER_COMPOSE_FILE=${DEPLOY_ENV}.$DOCKER_COMPOSE_FILE_NAME.yml;
    - echo $DOCKER_COMPOSE_FILE
    - echo $SWARM_NODES
    - git clone $DOCKER_COMPOSE_REPO_URL compose_repo
    - cp compose_repo/$DOCKER_COMPOSE_REPO_PATH/$DOCKER_COMPOSE_FILE $DOCKER_COMPOSE_FILE_PATH
    - sed -i "s/@CONFIG_VERSION/$(date +%s)/g" $DOCKER_COMPOSE_FILE_PATH/$DOCKER_COMPOSE_FILE
    - echo "===== SYNC docker-compose.yml ... ====="
    - echo "Remote path --> $WORKING_PATH/$DEPLOY_ENV/docker-compose.yml"
    - echo "Server --> $SERVER_IP"
    - curl -F jobid=$CI_JOB_ID -F env=$DEPLOY_ENV -F host=$SERVER_IP -F port=$SERVER_PORT -F user=$SERVER_USER -F remotePath="$WORKING_PATH/$DEPLOY_ENV/docker-compose.yml" -F file=@"$DOCKER_COMPOSE_FILE_PATH/$DOCKER_COMPOSE_FILE" $DEPLOYMENT_API/scp?token=$DEPLOY_API_TOKEN
    - echo $CONFIG_FILE_PATH/$CONFIG_FILE
    - ls -l $CONFIG_FILE_PATH
    - if [ ! -z "$CONFIG_FILE_NAME" ];
      then
        echo "===== SYNC $CONFIG_FILE ... =====";
        curl -F jobid=$CI_JOB_ID -F env=$DEPLOY_ENV -F host=$SERVER_IP -F port=$SERVER_PORT -F user=$SERVER_USER -F remotePath="$WORKING_PATH/$DEPLOY_ENV/configs/$CONFIG_DEST_FILE" -F file=@"$CONFIG_FILE_PATH/$CONFIG_FILE" $DEPLOYMENT_API/scp?token=$DEPLOY_API_TOKEN;
      fi
    - if [ ! -z "$SP_FILE_NAME" ];
      then
        echo $SP_FILE_COMPOSE;
        if [ $SP_FILE_COMPOSE == "disabled" ]; then
          export SP_ENV=${DEPLOY_ENV};
        else
          export SP_ENV=$(echo ${DEPLOY_ENV}| cut -d'_' -f 1);
        fi;
        export SP_FILE=$SP_FILE_NAME.${SP_ENV}.$SP_FILE_EXTENSION;
        echo "===== SYNC $SP_FILE ... =====";
        curl -F jobid=$CI_JOB_ID -F env=$DEPLOY_ENV -F host=$SERVER_IP -F port=$SERVER_PORT -F user=$SERVER_USER -F remotePath="$WORKING_PATH/$DEPLOY_ENV/configs/$SP_FILE_NAME.$SP_FILE_EXTENSION" -F file=@"$SP_FILE_PATH/$SP_FILE" $DEPLOYMENT_API/scp?token=$DEPLOY_API_TOKEN;
      fi
    - echo "===== DEPLOYING SERVICE ... =====";
    #- curl -F jobid=$CI_JOB_ID -F env=$DEPLOY_ENV -F host=$SERVER_IP -F port=$SERVER_PORT -F user=$SERVER_USER -F command="docker service rm ${SERVICE_NAME}_${DEPLOY_ENV} || true" $DEPLOYMENT_API/command?token=$DEPLOY_API_TOKEN
    - curl --fail -F jobid=$CI_JOB_ID -F env=$DEPLOY_ENV -F host=$SERVER_IP -F port=$SERVER_PORT -F user=$SERVER_USER -F command="cd $WORKING_PATH/$DEPLOY_ENV  && docker stack deploy --compose-file=docker-compose.yml --with-registry-auth $STACK_NAME" $DEPLOYMENT_API/command?token=$DEPLOY_API_TOKEN;
    - echo "===== REMOVING OLD CONFIGS ... =====";
    - if [ ! -z "$SP_FILE_NAME" ];
      then
        curl -F jobid=$CI_JOB_ID -F env=$DEPLOY_ENV -F host=$SERVER_IP -F port=$SERVER_PORT -F user=$SERVER_USER -F command="docker config rm $(docker config ls | grep -e ${SERVICE_NAME}_${DEPLOY_ENV}_sp_config*) || true" $DEPLOYMENT_API/command?token=$DEPLOY_API_TOKEN;
      fi
    - curl -F jobid=$CI_JOB_ID -F env=$DEPLOY_ENV -F host=$SERVER_IP -F port=$SERVER_PORT -F user=$SERVER_USER -F command="docker config rm $(docker config ls | grep -e ${SERVICE_NAME}_${DEPLOY_ENV}_config*) || true" $DEPLOYMENT_API/command?token=$DEPLOY_API_TOKEN;
  after_script:
    - curl --request DELETE --header "PRIVATE-TOKEN:$CI_JOB_TOKEN" $GITLAB_API_URL/projects/$CI_PROJECT_ID/repository/tags/$CI_COMMIT_TAG
  tags:
    - docker
