before_script:
  - docker info
  - echo $CURRENT_TAG
  - if echo "$CI_COMMIT_TAG" | grep -q "$CURRENT_TAG";
    then
      export DEPLOY_ENV=$CI_ENVIRONMENT_NAME;
      echo "Continue deploying";
    elif [ "$CI_COMMIT_BRANCH" == "master" ]; 
    then
      export DEPLOY_ENV=PROD;
      echo "Continue deploying";
    else
      echo "This job has tag is not used for current repository";
      exit 1;
    fi
  - eval $(ssh-agent -s)
  - echo "$SSH_KEY" | ssh-add -
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - export COMMIT_MESSAGE=$(git log -1 --pretty=%B)
  - export CI_REGISTRY_IMAGE=$DOCKER_REG_URL/$DOCKER_IMAGE_PATH
  - export CI_REGISTRY_IMAGE_VERSION=${CI_COMMIT_SHA:0:8}
  - echo $CI_REGISTRY_IMAGE
  - export CONFIG_FILE=$CONFIG_FILE_NAME.${DEPLOY_ENV}.$CONFIG_FILE_EXTENSION