publish_npm:
    stage: publish
    image: node:14
    needs: ["sonarqube-check"]
    before_script:
        - apt-get update
        - apt-get upgrade -y
        - apt-get install -y git
    script:
        - npm install -g npm-cli-login
        - npm-cli-login -u luminet.ci -p 1qaz@WSX -e luminet.ci@luminetsoft.com -r http://npm.lumigame.com
        - npm set registry http://npm.lumigame.com
        - npm i
        - npx semantic-release
    tags:
        - docker
    rules:
        - if: '$CI_COMMIT_TAG =~ /^publish-\d{8}-\d+.*$/'
          when: always
        - if: '$CI_COMMIT_BRANCH == "master"'
          when: manual