.if-deploy-local: &if-deploy-local
  if: '$CI_COMMIT_TAG =~ /local/'

.if-deploy-sit: &if-deploy-sit
  if: '$CI_COMMIT_TAG =~ /sit/'

.if-deploy-uat: &if-deploy-uat
  if: '$CI_COMMIT_TAG =~ /uat/'
  
unit-test-dotnet:
  stage: test
  image: registry.nexdev.net:5050/docker/dotnet/core/sdk:3.1
  tags:
    - docker
  before_script:
    - dotnet tool install --global coverlet.console --version 1.7.2
    - export PATH="$PATH:/root/.dotnet/tools"
  script:
    - dotnet build
    - dotnet test --test-adapter-path:. --logger:"trx" || true
    - for path in $(find ./ -name '*Tests.dll');
      do
      if echo $path | grep 'bin';
      then
      coverlet $path --target "dotnet" --targetargs "test --no-build" --format opencover;
      fi
      done
  artifacts:
    when: always
    paths:
      - ./**/*.trx
      - ./**/*coverage.opencover.xml
    expire_in: 1 day
  allow_failure: true
  rules:
    - <<: *if-deploy-local
      when: never
    - <<: *if-deploy-sit
      when: never
    - <<: *if-deploy-uat
      when: never
    - when: always
