.build_image:
  stage: build
  script:
    - docker login -u $DOCKER_REG_USERNAME -p $DOCKER_REG_PASSWORD $DOCKER_REG_URL
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build
      --pull
      -f Dockerfile
      --tag $CI_REGISTRY_IMAGE:$CI_REGISTRY_IMAGE_VERSION
      --cache-from $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_REGISTRY_IMAGE_VERSION
    - docker tag $CI_REGISTRY_IMAGE:$CI_REGISTRY_IMAGE_VERSION $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  tags:
    - docker
