.base_deploy_swarm_service:
  stage: deploy
  script:
    - echo "Sync config to swarm nodes"
    - echo ${PROXY_SSH_COMMAND}
    - ${PROXY_SSH_COMMAND} ssh $SERVER_USER@$SERVER_IP
      docker network create -d overlay $DOCKER_NETWORK_NAME || true
    - >
      for NODE in $SWARM_NODES;
      do 
        ${PROXY_SSH_COMMAND} ssh $SERVER_USER@$NODE "mkdir -p $WORKING_PATH";
        if [ "$DEPLOY_ENV" == "LOCAL" ] && [ ${CONFIG_FILE} != "" ]; 
        then
          echo "Deploy LOCAL";
          scp $CONFIGS_SRC_DIR_PATH/$CONFIG_FILE $SERVER_USER@$NODE:$WORKING_PATH;
        elif [ ${CONFIG_FILE} != "" ]; 
        then
          echo "Deploy KBT";
          scp -P $SERVER_PORT -o ProxyCommand="ssh -p $KBT_PROXY_SSH_PORT -W %h:%p $KBT_PROXY_USER@$KBT_PROXY_ADDRESS" $CONFIGS_SRC_DIR_PATH/$CONFIG_FILE $SERVER_USER@$SERVER_IP:$WORKING_PATH;
        else
          echo "Not copying config file";
        fi
        ${PROXY_SSH_COMMAND} ssh $SERVER_USER@$NODE docker login -u $DOCKER_REG_USERNAME -p $DOCKER_REG_PASSWORD $DOCKER_REG_URL;
        ${PROXY_SSH_COMMAND} ssh $SERVER_USER@$NODE docker pull $CI_REGISTRY_IMAGE:$CI_REGISTRY_IMAGE_VERSION;
      done
    - export CREATE_SERVICE_CMD="docker service create
        --mode replicated
        --replicas $SWARM_REPLICAS
        --name $DOCKER_SERVICE_NAME-$DEPLOY_ENV
        --network $DOCKER_NETWORK_NAME
        --endpoint-mode dnsrr
        --constraint node.labels.$NODE_LABEL==yes"
    - if [ ${CONFIG_FILE} != "" ]; 
      then
        export CREATE_SERVICE_CMD="${CREATE_SERVICE_CMD} --mount type=bind,source=$WORKING_PATH/$CONFIG_FILE,target=$CONFIG_CONTAINER_PATH,ro=true";
      else
        echo "Not mount config file";
      fi
    - export CREATE_SERVICE_CMD="${CREATE_SERVICE_CMD} $CI_REGISTRY_IMAGE:$CI_REGISTRY_IMAGE_VERSION"
    - echo $CREATE_SERVICE_CMD
    - ${PROXY_SSH_COMMAND} ssh $SERVER_USER@$SERVER_IP
      "if docker service ls | grep $DOCKER_SERVICE_NAME-$DEPLOY_ENV;
      then
        echo "Updating service";
        docker service update --image	$CI_REGISTRY_IMAGE:$CI_REGISTRY_IMAGE_VERSION $DOCKER_SERVICE_NAME-$DEPLOY_ENV;
      else
        echo "Creating service";
        $CREATE_SERVICE_CMD;
      fi"
  tags:
    - docker
