.base_deploy_local:
  stage: deploy
  script:
    - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP
      "(docker login -u $DOCKER_REG_USERNAME -p $DOCKER_REG_PASSWORD $DOCKER_REG_URL)
      && docker pull $CI_REGISTRY_IMAGE:$CI_REGISTRY_IMAGE_VERSION
      && (docker rm -f $DOCKER_SERVICE_NAME-$DEPLOY_ENV || true)
      && (docker network create $DOCKER_NETWORK_NAME || true)"
    - if [ "$DOCKER_PUBLIC_PORT" == "" ];
      then
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP
        "docker run --restart=always --name $DOCKER_SERVICE_NAME-$DEPLOY_ENV --network $DOCKER_NETWORK_NAME -d $CI_REGISTRY_IMAGE:$CI_REGISTRY_IMAGE_VERSION";
      else
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP
        "docker run --restart=always --name $DOCKER_SERVICE_NAME-$DEPLOY_ENV --network $DOCKER_NETWORK_NAME -p $DOCKER_PUBLIC_PORT:$DOCKER_PRIVATE_PORT -d $CI_REGISTRY_IMAGE:$CI_REGISTRY_IMAGE_VERSION";
      fi
  tags:
    - docker

.base_deploy_kbt:
  extends:
    - .base_deploy_local
  script:
    - ssh -p $KBT_PROXY_SSH_PORT -t $KBT_PROXY_USER@$KBT_PROXY_ADDRESS ssh -p $SERVER_PORT $SERVER_USER@$SERVER_IP docker login -u $DOCKER_REG_USERNAME -p $DOCKER_REG_PASSWORD $DOCKER_REG_URL
    - ssh -p $KBT_PROXY_SSH_PORT -t $KBT_PROXY_USER@$KBT_PROXY_ADDRESS ssh -p $SERVER_PORT $SERVER_USER@$SERVER_IP docker pull $CI_REGISTRY_IMAGE:$CI_REGISTRY_IMAGE_VERSION
    - ssh -p $KBT_PROXY_SSH_PORT -t $KBT_PROXY_USER@$KBT_PROXY_ADDRESS ssh -p $SERVER_PORT $SERVER_USER@$SERVER_IP docker rm -f $DOCKER_SERVICE_NAME-$DEPLOY_ENV || true
    - if [ "$DOCKER_PUBLIC_PORT" == "" ];
      then
        ssh -p $KBT_PROXY_SSH_PORT -t $KBT_PROXY_USER@$KBT_PROXY_ADDRESS ssh -p $SERVER_PORT $SERVER_USER@$SERVER_IP docker run --restart=always --name $DOCKER_SERVICE_NAME-$DEPLOY_ENV -d $CI_REGISTRY_IMAGE:$CI_REGISTRY_IMAGE_VERSION;
      else
        ssh -p $KBT_PROXY_SSH_PORT -t $KBT_PROXY_USER@$KBT_PROXY_ADDRESS ssh -p $SERVER_PORT $SERVER_USER@$SERVER_IP docker run --restart=always --name $DOCKER_SERVICE_NAME-$DEPLOY_ENV -p $DOCKER_PUBLIC_PORT:$DOCKER_PRIVATE_PORT -d $CI_REGISTRY_IMAGE:$CI_REGISTRY_IMAGE_VERSION;
      fi
