.deploy:local:base:swarm:stack:
  extends:
    - .deploy:local:swarm:stack
  variables:
    SERVER_IP: $SC_SWARM_LEADER_LOCAL
    SERVER_USER: $SC_SWARM_LEADER_LOCAL_SSH_USER
    SERVER_PORT: $SC_SWARM_LEADER_LOCAL_SSH_PORT
    SWARM_NODES: $SC_SWARM_CLUSTER_LOCAL

.deploy:local1:base:swarm:stack:
  extends:
    - .deploy:local1:swarm:stack
  variables:
    SERVER_IP: $SC_SWARM_LEADER_LOCAL
    SERVER_USER: $SC_SWARM_LEADER_LOCAL_SSH_USER
    SERVER_PORT: $SC_SWARM_LEADER_LOCAL_SSH_PORT
    SWARM_NODES: $SC_SWARM_CLUSTER_LOCAL

.deploy:local2:base:swarm:stack:
  extends:
    - .deploy:local2:swarm:stack
  variables:
    SERVER_IP: $SC_SWARM_LEADER_LOCAL
    SERVER_USER: $SC_SWARM_LEADER_LOCAL_SSH_USER
    SERVER_PORT: $SC_SWARM_LEADER_LOCAL_SSH_PORT
    SWARM_NODES: $SC_SWARM_CLUSTER_LOCAL

.deploy:local3:base:swarm:stack:
  extends:
    - .deploy:local3:swarm:stack
  variables:
    SERVER_IP: $SC_SWARM_LEADER_LOCAL
    SERVER_USER: $SC_SWARM_LEADER_LOCAL_SSH_USER
    SERVER_PORT: $SC_SWARM_LEADER_LOCAL_SSH_PORT
    SWARM_NODES: $SC_SWARM_CLUSTER_LOCAL
