image: git3.nexdev.net:5050/lumi-ops/docker-images/docker:19.03.12

before_script:
  #  - docker info
  - echo $CURRENT_TAG
  - if echo "$CI_COMMIT_TAG" | grep -q "$CURRENT_TAG";
    then
    export DEPLOY_ENV=$CI_ENVIRONMENT_NAME;
    echo "Continue deploying";
    elif [ "$CI_COMMIT_BRANCH" == "master" ];
    then
    export DEPLOY_ENV=PROD;
    echo "Continue deploying";
    else
    echo "This job has tag is not used for current repository";
    exit 1;
    fi
  - eval $(ssh-agent -s)
  - echo "$SSH_KEY" | ssh-add -
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - export COMMIT_MESSAGE=$(git log -1 --pretty=%B)
  - export CI_REGISTRY_IMAGE=$DOCKER_REG_URL/$DOCKER_IMAGE_PATH
  - export CI_REGISTRY_IMAGE_VERSION=${CI_COMMIT_SHA:0:8}
  - echo $CI_REGISTRY_IMAGE
  - export CONFIG_FILE=$CONFIG_FILE_NAME.${DEPLOY_ENV}.$CONFIG_FILE_EXTENSION
  - if [ "$DOCKER_FILE_PATH" == "" ];
    then
    export DOCKER_FILE_PATH=".";
    else
    export DOCKER_FILE_PATH=$DOCKER_FILE_PATH;
    fi
  - echo $DOCKER_FILE_PATH
  - export CONFIG_FILE=$CONFIG_FILE_NAME.${DEPLOY_ENV}.$CONFIG_FILE_EXTENSION
  - if [ "$DOCKER_FILE_NAME" == "" ];
    then
    export DOCKER_FILE_NAME="Dockerfile";
    else
    export DOCKER_FILE_NAME=$DOCKER_FILE_NAME;
    fi
  - echo $DOCKER_FILE_NAME
  - if [ "$DOCKER_NETWORK_NAME" == "" ];
    then
    export DOCKER_NETWORK_NAME="bridge";
    else
    export DOCKER_NETWORK_NAME=$DOCKER_NETWORK_NAME;
    fi
  - echo $DOCKER_NETWORK_NAME
  - if [ "$DEPLOY_ENV" == "LOCAL" ] || [ "$DEPLOY_ENV" == "LOCAL-1" ];
    then
    export PROXY_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -p $SC_SWARM_LEADER_LOCAL_SSH_PORT -W %h:%p -q $SC_SWARM_LEADER_LOCAL_SSH_USER@$SC_SWARM_LEADER_LOCAL";
    else
    export PROXY_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -p $KBT_PROXY_SSH_PORT -W %h:%p -q $KBT_PROXY_USER@$KBT_PROXY_ADDRESS";
    fi
  - echo $PROXY_SSH_COMMAND
  - if [ "$PROJECT_WORKING_PATH" == "" ];
    then
    echo "$WORKING_PATH"
    else
    export WORKING_PATH=/var/www$PROJECT_WORKING_PATH;
    fi
  - if [ "$SERVICE_NAME" == "" ];
    then
    echo "$DOCKER_SERVICE_NAME"
    else
    export DOCKER_SERVICE_NAME=$SERVICE_NAME
    fi
