publish_npm:
    stage: publish
    image: registry.nexdev.net:5050/docker/node:14.16
    needs: ["sonarqube-check"]
    before_script:
        - apt-get update
        - apt-get upgrade -y
        - apt-get install -y git
    script:
        - npm install -g npm-cli-login
        - npm install -g yarn
        - npm-cli-login -u $NPM_LUMI_USER_NAME -p $NPM_LUMI_USER_PASSWORD -e $NPM_LUMI_USER_EMAIL -r $NPM_LUMI_HOST
        - npm set registry $NPM_LUMI_HOST
        - yarn install
        - npm run reg
        - npm run build
        - npx semantic-release
    tags:
        - docker
    rules:
        - if: '$CI_COMMIT_BRANCH == "master"'
          when: always